name: Build with lualatex
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile main-german.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: spack.tex
          compiler: lualatex
          args:
